version: '3.5'

services:
  wdrive-nginx:
    image: nginx:latest
    container_name: wdrive-nginx
    restart: always
    ports:
      - '127.0.0.1:${NGINX_PORT}:${NGINX_PORT}'
    networks:
      - nwk
    volumes:
      - ./nginx/:/etc/nginx/templates/
    environment:
      - NGINX_PORT=${NGINX_PORT}
      - NEXT_PORT=${NEXT_PORT}
      - EXPRESS_PORT=${EXPRESS_PORT}
  wdrive-next:
    container_name: wdrive-next
    build:
      context: next
    restart: always
    ports:
      - "127.0.0.1:${NEXT_PORT}:${NEXT_PORT}"
    networks:
      - nwk
    environment:
      - NEXT_PORT=${NEXT_PORT}
  wdrive-express:
    container_name: wdrive-express
    build: 
      context: express
    restart: always
    networks:
      - nwk
    ports:
      - '127.0.0.1:${EXPRESS_PORT}:${EXPRESS_PORT}'
    environment:
      - 'EXPRESS_PORT=${EXPRESS_PORT}'
      - 'BASE_URL=${BASE_URL}'
      - 'MORALIS_API_KEY=${MORALIS_API_KEY}'

networks:
  nwk:
    driver: bridge
