version: '3.5'

services:
  wdrive-nginx:
    container_name: nginx
    build: nginx
    restart: always
    ports:
      - '127.0.0.1:33:33'
    networks:
      - app
  wdrive-next:
    container_name: next
    build:
      context: next
    restart: always
    ports:
      - "127.0.0.1:${NEXT_PORT}:${NEXT_PORT}"
    networks:
      - app
  wdrive-express:
    container_name: express
    build: 
      context: express
    restart: always
    networks:
      - app
    ports:
      - '127.0.0.1:${EXPRESS_PORT}:${EXPRESS_PORT}'
    environment:
      - 'EXPRESS_PORT=${EXPRESS_PORT}'
      - 'BASE_URL=${BASE_URL}'
      - 'MORALIS_API_KEY=${MORALIS_API_KEY}'

networks:
  app:
    driver: bridge
