version: '3.5'

services:
  nginx:
    container_name: nginx
    build: nginx
    restart: always
    ports:
      - '81:81'
    networks:
      - app
  next:
    container_name: next
    build:
      context: next
    restart: always
    ports:
      - "${NEXT_PORT}:${NEXT_PORT}"
    networks:
      - app
  express:
    container_name: express
    build: 
      context: express
    restart: always
    networks:
      - app
    ports:
      - '${EXPRESS_PORT}:${EXPRESS_PORT}'
    environment:
      - 'EXPRESS_PORT=${EXPRESS_PORT}'
      - 'BASE_URL=${BASE_URL}'
      - 'MORALIS_API_KEY=${MORALIS_API_KEY}'

networks:
  app:
    driver: bridge
